### ISSUE TITLE
Add Enroot by Nvidia

### ISSUE THREAD

**Issue by marcodelapierre** [pditommaso/awesome-containers#2]
hey Paolo,

I'd suggest you add the following runtime:

Enroot - A simple, yet powerful tool to turn traditional container/OS images into unprivileged sandboxes.
https://github.com/nviDIA/enroot

Not the best container engine I know, but possibly worth a mention.

**Comment by pditommaso** [comment]
Fair enough! e16abd6. Thanks for mentioning!
